### ISSUE TITLE
Docs: Screenshot doesn't match the description

### ISSUE THREAD

**Issue by lurch** [RPi-Distro/python-sense-emu#12]
While reading https://sense-emu.readthedocs.io/en/v1.0/sense_emu_gui.html I noticed that the screenshot appears to be different to what the text below it describes...

> At the top right, three sliders represent the temperature, pressure, and humidity...

> Finally, at the bottom left of the window, three sliders provide the orientation...

I'm afraid I've not actually tried running the emulator yet, so I dunno if it's the screenshot which is out of date, or the descriptions ;-)

I also noticed that https://sense-emu.readthedocs.io/en/v1.0/examples.html#joystick has `#!/usr/bin/python3` at the top, which none of the other examples on that page do.

**Comment by waveform80** [comment]
Definitely the descriptions - it's rare I write docs before code ;)
