### ISSUE TITLE
compass raw data is only noise 

### ISSUE THREAD

**Issue by TweetPete** [RPi-Distro/python-sense-emu#18]
Hii, at first great work. It’s super handy tool for experimenting with sensor data.
After testing a little bit I noticed some problems. I was trying to get gyroscope raw data, but I couldn’t notice a significant change in the values by turning the hat, only noise. Accelerometer works fine apparently.

I’m using Chrome 57.0.2987.133 (64-bit) and my code looks like this:

    from sense_hat import SenseHat
    from time import sleep

    sense = SenseHat()
    sense.set_imu_config(False, True, False)

    while(True):
        gyro_raw = sense.get_gyroscope_raw()
        print(“x: {x}, y: {y}, z: {z}”.format(**gyro_raw))
        sleep(1)

Kind regards
Peter

**Comment by waveform80** [comment]
Sorry, this repo is for the desktop Sense HAT emulator; your issue is with the web emulator which is a distinct piece of software. I'm not entirely sure where reports for that go; @bennuttall any ideas?
