### ISSUE TITLE
Orientation sliders require mouse over to update

### ISSUE THREAD

**Issue by davidhoness** [RPi-Distro/python-sense-emu#2]
After changing the range preference for the Orientation sliders they do not change until a mouse over event occurs. I wonder if this would be fixed by manually firing that even after the preferences have been closed?

**Comment by waveform80** [comment]
Fixed in 420378d339d18f0ddb79128b06b8eaf62f2e1b32 (I'd originally attempted to fix this in a0e0a150b21eb338a4987e2213c2a6fdb8462106 but while that worked on Ubuntu, it didn't on Raspbian) - new fix works on both
