### ISSUE TITLE
Ctrl + C kills spawned GUI when launched from shell

### ISSUE THREAD

**Issue by bennuttall** [RPi-Distro/python-sense-emu#22]
When the GUI is automatically spawned from a Python shell, any keyboard interrupt will silently kill the GUI.

To reproduce:

1. Open a Python shell
1. Import `sense_emu` and create a `SenseHat` object:

    ```python
    from sense_emu import SenseHat
    sense = SenseHat()
    ``` 
    
    (A GUI will be spawned automatically)

1. Run a while loop, e.g:

    ```python
    while True:
        print(1)
    ```

1. Hit Ctrl + C to terminate the loop
1. Try to update the Sense Hat display:

    ```python
    sense.clear(255, 0, 0)
     ```

    (the LEDs on the display should go red, but they don't)

1. Re-initialise the GUI:

    ```python
    sense = SenseHat()
    ```

    (note the leds are now red)

1. Try to update the display again:

    ```python
    sense.clear()
    ```

    (this should (and does) clear the leds)

It seems that killing the while loop also kills the GUI process spawned from the shell.

**Comment by waveform80** [comment]
This is because signals are sent to the process group on Linux/UNIX (and Windows? Not sure). Easy enough to fix with setpgrp - I'll push something in a mo.
