### ISSUE TITLE
Orientation sliders quite small on Raspbian

### ISSUE THREAD

**Issue by davidhoness** [RPi-Distro/python-sense-emu#9]
![dave](https://cloud.githubusercontent.com/assets/6640424/18096777/5912b640-6ed3-11e6-8a30-e8db2abc2e79.png)

Can the window be a bit larger by default?
Let me know if this is an artefact from having a previous version installed.

**Comment by waveform80** [comment]
I haven't discovered a "good" way yet. For example, I can set the minimum size to be a bit bigger horizontally (which is what's really needed for the orientation sliders) but I don't really want to limit the *minimum* size of the window as that prevents it being used in a variety of situations (half/quarter display which I frequently use when developing, and which is commonly applicable on a variety of OS' these days by dragging windows to the screen sides). It'd be nice to set to the *default* size but only if the display is definitely larger than the default size - haven't discovered how to do that on GTK yet.

**Comment by davidhoness** [comment]
Okay fair enough. Can we make the window size/state persist in the GTK settings for the program instead?

**Comment by waveform80** [comment]
I can do, but I figure getting the package built is the priority? This'll have to wait for the next release unfortunately.

**Comment by waveform80** [comment]
PR #15 also includes a fix for this now
